name: 'Checkov Scan'
description: 'Runs Checkov scan on the specified IaC directory.'

inputs:
  aws-role-arn:
    description: "ARN of the role to be assumed (e.g., arn:aws:iam::111122223333:role/github-oidc-role)"
    required: true

  aws-region:
    description: "AWS region where the services will be deployed (e.g., us-east-1)"
    required: true

  iac-dir:
    description: "The directory path of the IAC file."
    required: true

  iac-framework:
    description: "IAC Framework - Accepted values: cloudformation, terraform, kubernetes etc."
    required: true
    default: "cloudformation"

  soft-fail:
    description: "If true, Checkov scan will not fail the pipeline"
    required: false
    default: true

  github-token:
    description: 'GitHub token (optional, not used currently)'
    required: false

outputs:
  valid-template:
    description: 'Specifies if the template is valid'
    value: ${{ steps.validate-template.outputs.valid-template }}

  validation-error:
    description: 'Validation error message if any'
    value: ${{ steps.validate-template.outputs.validation-error }}

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure AWS credentials from AWS account
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        aws-region: ${{ inputs.aws-region }}
        role-session-name: github-aws-${{ inputs.iac-framework }}-oidc

    - name: Run Checkov Scan
      uses: bridgecrewio/checkov-action@master
      with:
        directory: ${{ github.workspace }}/${{ inputs.iac-dir }}
        soft_fail: ${{ inputs.soft-fail }}
        quiet: true
        framework: ${{ inputs.iac-framework }}
        output_format: sarif
        sarif_output_file: results.sarif  # Output file for SARIF format, must be named as results.sarif for the report action to work