name: "Reusable Checkov IaC Scan"
description: "Reusable GitHub Action to run Checkov against a specified IaC directory for security and compliance checks."

inputs:
  release-tag:
    description: "Git release tag to check out. If omitted, the latest commit on the default branch is used."
    required: false
    type: string

  iac-dir:
    description: "The directory path of the IAC file."
    required: true
    type: string
    default: "iac"

  iac-framework:
    description: "IAC Framework - Accepted values: cloudformation, terraform, kubernetes etc."
    required: true
    type: string
    default: "cloudformation"

  soft-fail:
    description: "If true, Checkov scan will not fail the pipeline"
    required: false
    type: boolean
    default: true

runs:
  using: "composite"
  steps:
    - name: "Set Checkout Ref"
      id: set-ref
      shell: bash
      run: |
        if [[ -n "${{ inputs.release-tag }}" ]]; then
          echo "ref=${{ inputs.release-tag }}" >> $GITHUB_OUTPUT
        else
          echo "ref=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
        fi

    - name: "Checkout Repo"
      id: checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.set-ref.outputs.ref }}

    - name: Ensure results.sarif is clean
      id: clean-results
      shell: bash
      run: |
        if [ -d "results.sarif" ]; then
          echo "Removing existing results.sarif directory..."
          rm -rf results.sarif
        fi

    - name: "Run Checkov Scan"
      id: checkov-scan
      uses: bridgecrewio/checkov-action@master
      with:
        directory: ${{ github.workspace }}/${{ inputs.iac-dir }}
        soft_fail: ${{ inputs.soft-fail }}
        quiet: "true"
        framework: ${{ inputs.iac-framework }}
        # Output file for SARIF format, must be named as results.sarif for the report action to work
        output_format: "sarif"
